/* Project 1
 * Author: Endalkachew Filfilu
 * Date: 07/28/2021
 * The intent: The supplier order is custom object
 * This class will access the Object and the fields
 * the task will be implementing the page that displays
   the fields  with customized view on visualforce page
*/

public class StorePage {
    
    public List<Supplier_Order__c> supplierList = new List<Supplier_Order__c>();
    
    

}